name: excavate-ht
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9,<3.13
  - bowtie>=1.2.3
  - bedtools
  - bcftools
  - pandas
  - numpy
  - biopython
  - regex
  - pyfaidx
  - pip